### ISSUE TITLE
Tmod loader uses dotnet.exe

### ISSUE THREAD

**Issue by Waaterbottle** [RussDev7/Izzy-s-Ultimate-Fishing-Toolkit#1]
The Tmod variant of the mod does not work because tmod uses dotnet.exe now instead of tmodloader.exe
Located in: 
P:\SteamLibrary\steamapps\common\tModLoader\dotnet\6.0.0

**Comment by RussDev7** [comment]
I will upload a TModLoader version of this mod to the GitHub. Thanks for the report.

**Comment by RussDev7** [comment]
I have added two versions of the TModLoader source codes (`tmodloader.exe` and `dotnet.exe`) and added both executables for download in the 1.40 release.

**Comment by Waaterbottle** [comment]
The different version is working. Thank you so much!
